USE [SARH]
GO
/****** Object:  Table [dbo].[Reserva]    Script Date: 08/02/2026 11:27:49 ******/
DROP TABLE IF EXISTS [dbo].[Reserva]
GO
/****** Object:  User [admin_sarh]    Script Date: 08/02/2026 11:27:49 ******/
DROP USER IF EXISTS [admin_sarh]
GO
USE [master]
GO
/****** Object:  Login [admin_sarh]    Script Date: 08/02/2026 11:27:49 ******/
IF  EXISTS (SELECT * FROM sys.server_principals WHERE name = N'admin_sarh')
DROP LOGIN [admin_sarh]
GO
/****** Object:  Database [SARH]    Script Date: 08/02/2026 11:27:49 ******/
DROP DATABASE IF EXISTS [SARH]
GO
/****** Object:  Database [SARH]    Script Date: 08/02/2026 11:27:49 ******/
CREATE DATABASE [SARH]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SARH', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\SARH.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SARH_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\SARH_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [SARH] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SARH].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [SARH] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SARH] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SARH] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SARH] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SARH] SET ARITHABORT OFF 
GO
ALTER DATABASE [SARH] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [SARH] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SARH] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SARH] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SARH] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SARH] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SARH] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SARH] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SARH] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SARH] SET  DISABLE_BROKER 
GO
ALTER DATABASE [SARH] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SARH] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SARH] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [SARH] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [SARH] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SARH] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [SARH] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [SARH] SET RECOVERY FULL 
GO
ALTER DATABASE [SARH] SET  MULTI_USER 
GO
ALTER DATABASE [SARH] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SARH] SET DB_CHAINING OFF 
GO
ALTER DATABASE [SARH] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [SARH] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [SARH] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [SARH] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'SARH', N'ON'
GO
ALTER DATABASE [SARH] SET QUERY_STORE = ON
GO
ALTER DATABASE [SARH] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
/****** Object:  Login [admin_sarh]    Script Date: 08/02/2026 11:27:50 ******/
CREATE LOGIN [admin_sarh] WITH PASSWORD=N'231022', DEFAULT_DATABASE=[SARH], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [admin_sarh]
GO
USE [SARH]
GO
/****** Object:  User [admin_sarh]    Script Date: 08/02/2026 11:27:50 ******/
CREATE USER [admin_sarh] FOR LOGIN [admin_sarh] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_owner] ADD MEMBER [admin_sarh]
GO
GRANT CONNECT TO [admin_sarh] AS [dbo]
GO
GRANT VIEW ANY COLUMN ENCRYPTION KEY DEFINITION TO [public] AS [dbo]
GO
GRANT VIEW ANY COLUMN MASTER KEY DEFINITION TO [public] AS [dbo]
GO
/****** Object:  Table [dbo].[Reserva]    Script Date: 08/02/2026 11:27:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Reserva](
	[IDReserva] [int] NOT NULL,
	[IDHuesped] [varchar](10) NOT NULL,
	[IDHabitacion] [int] NOT NULL,
	[FechaIngreso] [date] NOT NULL,
	[FechaSalida] [date] NOT NULL,
	[NumeroNoches] [int] NOT NULL,
	[EstadoReserva] [varchar](12) NOT NULL,
 CONSTRAINT [PK__Reserva__D9F2FA67EAC7DFC9] PRIMARY KEY CLUSTERED 
(
	[IDReserva] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER AUTHORIZATION ON [dbo].[Reserva] TO  SCHEMA OWNER 
GO
INSERT [dbo].[Reserva] ([IDReserva], [IDHuesped], [IDHabitacion], [FechaIngreso], [FechaSalida], [NumeroNoches], [EstadoReserva]) VALUES (1022, N'0952306405', 11, CAST(N'2026-02-04' AS Date), CAST(N'2026-02-07' AS Date), 3, N'CONFIRMADA')
GO
INSERT [dbo].[Reserva] ([IDReserva], [IDHuesped], [IDHabitacion], [FechaIngreso], [FechaSalida], [NumeroNoches], [EstadoReserva]) VALUES (1133, N'0915599682', 55, CAST(N'2026-02-05' AS Date), CAST(N'2026-02-12' AS Date), 7, N'CONFIRMADA')
GO
INSERT [dbo].[Reserva] ([IDReserva], [IDHuesped], [IDHabitacion], [FechaIngreso], [FechaSalida], [NumeroNoches], [EstadoReserva]) VALUES (2211, N'0915599682', 231, CAST(N'2026-02-05' AS Date), CAST(N'2026-02-13' AS Date), 8, N'CONFIRMADA')
GO
INSERT [dbo].[Reserva] ([IDReserva], [IDHuesped], [IDHabitacion], [FechaIngreso], [FechaSalida], [NumeroNoches], [EstadoReserva]) VALUES (2212, N'2222222222', 22, CAST(N'2026-02-03' AS Date), CAST(N'2026-02-19' AS Date), 16, N'PENDIENTE')
GO
INSERT [dbo].[Reserva] ([IDReserva], [IDHuesped], [IDHabitacion], [FechaIngreso], [FechaSalida], [NumeroNoches], [EstadoReserva]) VALUES (2244, N'0950232323', 33, CAST(N'2026-02-05' AS Date), CAST(N'2026-02-12' AS Date), 7, N'PENDIENTE')
GO
INSERT [dbo].[Reserva] ([IDReserva], [IDHuesped], [IDHabitacion], [FechaIngreso], [FechaSalida], [NumeroNoches], [EstadoReserva]) VALUES (2310, N'0952871705', 22, CAST(N'2026-10-23' AS Date), CAST(N'2026-10-25' AS Date), 2, N'CONFIRMADA')
GO
INSERT [dbo].[Reserva] ([IDReserva], [IDHuesped], [IDHabitacion], [FechaIngreso], [FechaSalida], [NumeroNoches], [EstadoReserva]) VALUES (3311, N'0992982142', 66, CAST(N'2026-02-05' AS Date), CAST(N'2026-02-07' AS Date), 2, N'PENDIENTE')
GO
USE [master]
GO
ALTER DATABASE [SARH] SET  READ_WRITE 
GO